// Code generated by "stringer -type=RecordEncryption"; DO NOT EDIT

package airport

import "fmt"

const (
	_RecordEncryption_name_0 = "EncryptionUnencrypted"
	_RecordEncryption_name_1 = "EncryptionEncrypted"
)

var (
	_RecordEncryption_index_0 = [...]uint8{0, 21}
	_RecordEncryption_index_1 = [...]uint8{0, 19}
)

func (i RecordEncryption) String() string {
	switch {
	case i == 0:
		return _RecordEncryption_name_0
	case i == 2:
		return _RecordEncryption_name_1
	default:
		return fmt.Sprintf("RecordEncryption(%d)", i)
	}
}
