// Code generated by "stringer -type=RecordType"; DO NOT EDIT

package airport

import "fmt"

const _RecordType_name = "TypeCharStringTypeIPAddressTypeByteStringTypePhoneNumberTypeUnsignedIntegerTypeByteTypeLittleEndianUnsignedInteger"

var _RecordType_index = [...]uint8{0, 14, 27, 41, 56, 75, 83, 114}

func (i RecordType) String() string {
	if i < 0 || i >= RecordType(len(_RecordType_index)-1) {
		return fmt.Sprintf("RecordType(%d)", i)
	}
	return _RecordType_name[_RecordType_index[i]:_RecordType_index[i+1]]
}
