package airport

var tags = map[string]InfoRecord{
	"syPR": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Read community",
		Tag:         "syPR",
	},
	"syPW": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Read/write community",
		Tag:         "syPW",
	},
	"waCV": InfoRecord{
		MaxLength:   4,
		DataType:    TypeByteString,
		Encryption:  EncryptionUnencrypted,
		Description: "Configuration mode",
		Tag:         "waCV",
	},
	"waIn": InfoRecord{
		MaxLength:   4,
		DataType:    TypeByteString,
		Encryption:  EncryptionUnencrypted,
		Description: "Ethernet/Modem switch 1",
		Tag:         "waIn",
	},
	"raRo": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Microwave robustness flag",
		Tag:         "raRo",
	},
	"raCl": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Closed network flag",
		Tag:         "raCl",
	},
	"raDe": InfoRecord{
		MaxLength:   4,
		DataType:    TypeByteString,
		Encryption:  EncryptionUnencrypted,
		Description: "Access point density",
		Tag:         "raDe",
	},
	"raMu": InfoRecord{
		MaxLength:   4,
		DataType:    TypeByteString,
		Encryption:  EncryptionUnencrypted,
		Description: "Multicast rate",
		Tag:         "raMu",
	},
	"raCh": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionUnencrypted,
		Description: "Wireless channel",
		Tag:         "raCh",
	},
	"moID": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionUnencrypted,
		Description: "Modem timeout",
		Tag:         "moID",
	},
	"moPD": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Dialing type (tone or pulse)",
		Tag:         "moPD",
	},
	"moAD": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Automatic dial",
		Tag:         "moAD",
	},
	"moCC": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionUnencrypted,
		Description: "Phone country code",
		Tag:         "moCC",
	},
	"moCI": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionUnencrypted,
		Description: "Modem country code combo box index",
		Tag:         "moCI",
	},
	"raNm": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Network name",
		Tag:         "raNm",
	},
	"moPN": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Primary phone number",
		Tag:         "moPN",
	},
	"moAP": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Secondary phone number",
		Tag:         "moAP",
	},
	"peID": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionUnencrypted,
		Description: "PPPoE idle timeout",
		Tag:         "peID",
	},
	"peAC": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "PPPoE auto connect",
		Tag:         "peAC",
	},
	"peSC": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "PPPoE stay connected",
		Tag:         "peSC",
	},
	"raWM": InfoRecord{
		MaxLength:   4,
		DataType:    TypeByteString,
		Encryption:  EncryptionUnencrypted,
		Description: "Encryption switch",
		Tag:         "raWM",
	},
	"raWE": InfoRecord{
		MaxLength:   13,
		DataType:    TypeByteString,
		Encryption:  EncryptionEncrypted,
		Description: "Encryption key",
		Tag:         "raWE",
	},
	"laIP": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Private LAN base station address",
		Tag:         "laIP",
	},
	"laSM": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Private LAN subnet mask",
		Tag:         "laSM",
	},
	"raWB": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Wireless to Ethernet bridging switch",
		Tag:         "raWB",
	},
	"acEn": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Access control switch",
		Tag:         "acEn",
	},
	"acTa": InfoRecord{
		MaxLength:   16,
		DataType:    TypeByteString,
		Encryption:  EncryptionEncrypted,
		Description: "Access control info",
		Tag:         "acTa",
	},
	"raDS": InfoRecord{
		MaxLength:   10,
		DataType:    TypeByte,
		Encryption:  EncryptionEncrypted,
		Description: "Wireless DHCP switch",
		Tag:         "raDS",
	},
	"laDS": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "LAN Ethernet DHCP switch",
		Tag:         "laDS",
	},
	"waDS": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionEncrypted,
		Description: "WAN Ethernet DHCP switch",
		Tag:         "waDS",
	},
	"raNA": InfoRecord{
		MaxLength:   1,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "NAT switch",
		Tag:         "raNA",
	},
	"waIP": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Base station IP address",
		Tag:         "waIP",
	},
	"waRA": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Router IP address",
		Tag:         "waRA",
	},
	"waSM": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Subnet mask",
		Tag:         "waSM",
	},
	"syCt": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Contact person name",
		Tag:         "syCt",
	},
	"syNm": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Base station name",
		Tag:         "syNm",
	},
	"syLo": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Base station location",
		Tag:         "syLo",
	},
	"waDC": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "DHCP client ID",
		Tag:         "waDC",
	},
	"dhBg": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "DHCP address range start",
		Tag:         "dhBg",
	},
	"dhEn": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "DHCP address range end",
		Tag:         "dhEn",
	},
	"waD1": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Primary DNS server",
		Tag:         "waD1",
	},
	"waD2": InfoRecord{
		MaxLength:   4,
		DataType:    TypeIPAddress,
		Encryption:  EncryptionEncrypted,
		Description: "Secondary DNS server",
		Tag:         "waD2",
	},
	"dhLe": InfoRecord{
		MaxLength:   4,
		DataType:    TypeUnsignedInteger,
		Encryption:  EncryptionEncrypted,
		Description: "DHCP lease time",
		Tag:         "dhLe",
	},
	"waDN": InfoRecord{
		MaxLength:   32,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Domain name",
		Tag:         "waDN",
	},
	"pmTa": InfoRecord{
		MaxLength:   16,
		DataType:    TypeByteString,
		Encryption:  EncryptionEncrypted,
		Description: "Port mapping",
		Tag:         "pmTa",
	},
	"moUN": InfoRecord{
		MaxLength:   64,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Dial-up username",
		Tag:         "moUN",
	},
	"moPW": InfoRecord{
		MaxLength:   64,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "Dial-up password",
		Tag:         "moPW",
	},
	"peUN": InfoRecord{
		MaxLength:   64,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "PPPoE username",
		Tag:         "peUN",
	},
	"pePW": InfoRecord{
		MaxLength:   64,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "PPPoE password",
		Tag:         "pePW",
	},
	"peSN": InfoRecord{
		MaxLength:   64,
		DataType:    TypeCharString,
		Encryption:  EncryptionEncrypted,
		Description: "PPPoE service name",
		Tag:         "peSN",
	},
	"acRB": InfoRecord{
		MaxLength:   0,
		DataType:    TypeByte,
		Encryption:  EncryptionUnencrypted,
		Description: "Reboot flag",
		Tag:         "acRB",
	},
	"buil": InfoRecord{
		MaxLength:   40,
		DataType:    TypeCharString,
		Encryption:  EncryptionUnencrypted,
		Description: "Software build hash",
		Tag:         "buil",
	},
}

// GetInfoRecord TODO
func GetInfoRecord(tag string) *InfoRecord {
	tagStruct := tags[tag]

	return &InfoRecord{
		MaxLength:   tagStruct.MaxLength,
		DataType:    tagStruct.DataType,
		Encryption:  tagStruct.Encryption,
		Description: tagStruct.Description,
		Tag:         tagStruct.Tag,
	}
}

// GetAllInfoRecords TODO
func GetAllInfoRecords() map[string]*InfoRecord {
	recs := make(map[string]*InfoRecord)
	for tag := range tags {
		recs[tag] = GetInfoRecord(tag)
	}
	return recs
}
